version: '3'
services:
  api:
    image: "node:8.9.4"
    ports:
      - "3000:3000"
      - "9229:9229"
    expose:
      - "8080"
      - "9229"
    volumes:
      - ./src:/usr/src/api
    entrypoint: /bin/bash ./usr/src/api/start.sh
  database:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  #database:
  #  image: mysql
  #  command: --default-authentication-plugin=mysql_native_password
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: example